# Address of proxy for clients to connect
Local_address = "0.0.0.0:19132"
# Address of origin server for proxy to relay
Remote_Address = "localhost:19133"
# Time in seconds of inactivity before connection will be closed
Timeout = 10
# Time in second of waiting before sending ping packet (and get motd) to origin server
Motd_get_interval = 10
# Whether use api server
Use_api_server = true
# Address of api server
Api_server_address = ":3030"
# Array of ip addresses that can use api. Keep it empty to allow any ip address
Api_whitelist = ["[::1]", "4.4.4.4"]