# Address of proxy for clients to connect
LocalAddress = "0.0.0.0:228"
# Address of origin server for proxy to relay
RemoteAddress = "localhost:19133"
# Time in seconds of inactivity before connection will be closed
Timeout = 60
# Time in second of waiting before sending ping packet (and get motd) to origin server
MotdGetInterval = 10
# Whether use api server
UseApiServer = true
# Address of api server
ApiServerAddress = ":3030"
# Array of ip addresses that can use api. Keep it empty to allow any ip address
ApiWhitelist = ["4.4.4.4"]
# Whether use prometheus server
UsePrometheus = true
# Address of prometheus server
PrometheusAddress = ":3031"
