name: Build project

on:
    push:
        branches: ["main"]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go 1.21
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21.x
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -o ./build/TheStoneProxy-${{ matrix.os }} .
            - uses: actions/upload-artifact@v3
              with:
                  name: TheStoneProxy
                  path: build/
