name: Build project

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .

  put-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: The StoneProxy
          path: TheStoneProxy